#!/usr/bin/env python3
"""PyTorch reference outputs, for checking the C engine.

The value of these is that they come from HuggingFace's implementation, not mine.
A numpy forward pass I wrote would share any misunderstanding with the C I am
checking -- the RoPE convention above all -- and would confirm a bug rather than
catch it.

Records more than final logits, because "the logits are wrong" is not a debuggable
statement. The per-layer checksums let a mismatch be bisected to a single block,
and the intermediate tensors inside layer 0 localise it further: if
post-attention already differs, the bug is in attention or RoPE; if only post-MLP
differs, it is SwiGLU.

    tools/.venv/bin/python tools/golden_logits.py
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import torch

REPO = "HuggingFaceTB/SmolLM2-135M-Instruct"
ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "engine" / "tests" / "fixtures" / "golden.json"

# Twelve tokens is enough to exercise RoPE at several positions and GQA across
# heads, while keeping the fixture small enough to commit and read.
SEQUENCE = [1, 9690, 198, 21350, 2029, 563, 2503, 30, 24310, 36748, 8515, 1015]

TOP_K = 50


def checksum(t: torch.Tensor) -> dict:
    """A few scalars that localise a mismatch without storing whole tensors."""
    a = t.detach().to(torch.float64).flatten()
    return {
        "sum": float(a.sum()),
        "abs_sum": float(a.abs().sum()),
        "sum_sq": float((a * a).sum()),
        "min": float(a.min()),
        "max": float(a.max()),
        "shape": list(t.shape),
    }


def main() -> int:
    from transformers import AutoModelForCausalLM

    torch.set_grad_enabled(False)
    model = AutoModelForCausalLM.from_pretrained(REPO, dtype=torch.float32)
    model.eval()

    ids = torch.tensor([SEQUENCE])

    # Hook layer 0 so the two halves of the block can be checked separately.
    captured: dict[str, torch.Tensor] = {}
    layer0 = model.model.layers[0]

    def grab(name):
        def hook(_mod, _inp, out):
            captured[name] = (out[0] if isinstance(out, tuple) else out).clone()
        return hook

    handles = [
        layer0.self_attn.register_forward_hook(grab("layer0_attn_out")),
        layer0.mlp.register_forward_hook(grab("layer0_mlp_out")),
        layer0.register_forward_hook(grab("layer0_out")),
    ]

    out = model(ids, output_hidden_states=True)
    for h in handles:
        h.remove()

    logits = out.logits[0].to(torch.float64).numpy()  # [seq, vocab]
    n_seq, n_vocab = logits.shape

    positions = []
    for pos in range(n_seq):
        row = logits[pos]
        order = np.argsort(-row)[:TOP_K]
        positions.append({
            "pos": pos,
            "token": SEQUENCE[pos],
            "argmax": int(order[0]),
            "top_ids": [int(i) for i in order],
            "top_logits": [round(float(row[i]), 5) for i in order],
            "logit_sum": float(row.sum()),
            "logit_max": float(row.max()),
        })

    golden = {
        "_comment": (
            "GENERATED by tools/golden_logits.py from HuggingFace's own forward "
            "pass. The C engine must reproduce argmax at every position and match "
            "top logits to ~1e-2. Layer-0 and hidden-state checksums exist so a "
            "mismatch can be bisected rather than merely observed."
        ),
        "repo": REPO,
        "dtype": "float32",
        "sequence": SEQUENCE,
        "n_vocab": int(n_vocab),
        "top_k": TOP_K,
        "tolerance": {
            "argmax": "exact at every position",
            "max_abs_logit_diff": 1e-2,
        },
        "positions": positions,
        # Bisection points inside layer 0: attention first, then the MLP.
        "layer0": {k: checksum(v) for k, v in captured.items()},
        # And one checksum per layer boundary, so a divergence can be localised to
        # the block where it starts.
        "hidden_states": [
            checksum(h) for h in out.hidden_states
        ],
    }

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(golden, indent=1) + "\n")

    size = OUT.stat().st_size
    print(f"wrote {OUT.relative_to(ROOT)}  {size:,} bytes")
    print(f"  sequence      {SEQUENCE}")
    print(f"  vocab         {n_vocab}")
    print(f"  argmax chain  {[p['argmax'] for p in positions]}")
    print(f"  layers        {len(out.hidden_states)} hidden states "
          f"(embeddings + {len(out.hidden_states) - 1} blocks)")
    print()
    print("  first 5 predictions at the final position:")
    last = positions[-1]
    for i in range(5):
        print(f"    {last['top_ids'][i]:6d}  {last['top_logits'][i]:8.4f}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
