#!/usr/bin/env python3
"""Split a .hslm into shards, with a manifest.

Sharding buys three things, and the third is why it is done even though the model
would fit in one file:

  1. A failed download resumes at a shard boundary rather than from zero.
  2. Shards can be fetched in parallel.
  3. It keeps hosting on GitHub Pages a one-constant change. 86.5 MB is under the
     100 MB per-file limit, but ~9 MB pieces are comfortably under it with room for
     a larger model later.

    tools/shard.py model.hslm --out site/model/
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

SHARD_BYTES = 9 * 1024 * 1024


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("model", type=Path)
    ap.add_argument("--out", type=Path, required=True)
    ap.add_argument("--shard-bytes", type=int, default=SHARD_BYTES)
    ap.add_argument("--name", default="smollm2-135m-hybrid")
    args = ap.parse_args()

    data = args.model.read_bytes()
    args.out.mkdir(parents=True, exist_ok=True)

    shards = []
    for i in range(0, len(data), args.shard_bytes):
        piece = data[i : i + args.shard_bytes]
        name = f"{args.name}-{len(shards):03d}.bin"
        (args.out / name).write_bytes(piece)
        shards.append({
            "name": name,
            "bytes": len(piece),
            "sha256": hashlib.sha256(piece).hexdigest(),
        })

    manifest = {
        "_comment": (
            "GENERATED by tools/shard.py. The browser fetches shards in order and "
            "streams each straight into wasm linear memory, so the weights are never "
            "held twice -- which is the difference between ~135 MB and ~220 MB of peak "
            "usage, and therefore between working and not working on a phone."
        ),
        "model": args.name,
        "bytes": len(data),
        "sha256": hashlib.sha256(data).hexdigest(),
        "shards": shards,
    }
    (args.out / "manifest.json").write_text(json.dumps(manifest, indent=1) + "\n")

    print(f"wrote {len(shards)} shards to {args.out}/")
    print(f"  total   {len(data):,} bytes ({len(data) / 1e6:.1f} MB)")
    print(f"  each    {args.shard_bytes / 1e6:.1f} MB (last {shards[-1]['bytes'] / 1e6:.1f} MB)")
    print(f"  sha256  {manifest['sha256'][:32]}...")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
